site_name: Циминтия Николай К33392
nav:
  - Home: index.md
  - "№1: Реализация серверного приложения.":
      - lab_1.md
  - "№2: Многопоточность.":
      - lab_2.md
  - "№3: Docker и очереди задач.":
      - lab_3.md
